apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: app-staging
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: app-staging
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io