apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-deployer-role
  namespace: app-prod
rules:
# Lecture pods + logs
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

# Déploiement (rolling update uniquement)
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update", "patch"]

# Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "update", "patch"]

# Ingress
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "patch"]